branches:
  only:
    - master
    - develop

skip_tags: true

shallow_clone: true

platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      QTDIR: C:\Qt\5.5\msvc2013_64

before_build:
  - cd c:\projects\yacas
  - cmake -H. -Bbuild -G "%CMAKE_GENERATOR%" -DENABLE_CYACAS_KERNEL=Off -DCMAKE_PREFIX_PATH="%QTDIR%"

build:
  project: build\ALL_BUILD.vcxproj
  
test_script:
  - cmd: msbuild "build\RUN_TESTS.vcxproj" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  
after_build:
  - cmake --build build --use-stderr --config "%CONFIGURATION%" --target PACKAGE
