CHAPTERS = ABIN-grammar.chapt MaintenanceHowto.chapt\
  Plugin_factory.chapt txt2yacasdoc.chapt

all: $(CHAPTERS) essays.html

%.chapt: %.txt
	perl ../manmake/txt2yacasdoc.pl < $< > $@

essays.html: $(CHAPTERS)
	../src/yacas -pc all.ys

clean:
	-rm *.chapt *.html core *~

