all: ABIN-grammar.chapt MaintenanceHowto.chapt essays.html

%.chapt: %.txt
	perl ../manmake/txt2yacasdoc.pl < $< > $@

essays.html: ABIN-grammar.chapt MaintenanceHowto.chapt
	../src/yacas -pc all.ys

clean:
	-rm *.chapt *.html core *~

